<dl class="form">

    <dt>
    <?php if($label) : ?>
        <label for="<?php echo $id;?>"><?php echo $label;?></label>
    <?php endif;?>
    </dt>
    <dd>
        <div xclass="dd-text">

        <select name="<?php echo $name;?>" id="<?php echo $id;?>"  class="form-control">
    <?php foreach($options as $option) : ?>
            <option value="<?php echo $option['value'];?>"<?php if($value == $option['value']) : ?> selected<?php endif;?>><?php echo $option['value'];?></option>
    <?php endforeach;?>
        </select>
        </div>

        <?php if(TRUE === isset($note) && $note) : ?>
        <p class="note"><?php echo $note;?></p>
        <?php endif; ?>

    </dd>

</dl>