<dl class="form">

    <dt>
    <?php if($label) : ?>
        <label for="<?php echo $id;?>"><?php echo $label;?></label>
    <?php endif;?>
    </dt>
    <dd>
        <div class="dd-text">
    <?php foreach($options as $key => $option) : ?>
    	<label>
            <input type="radio" name="<?php echo $name;?>" value="<?php echo $key;?>" id="<?php echo $option['key'];?>"<?php if($value == $option['value']) : ?> checked="checked"<?php endif;?>> <?php echo $option['value'];?>
            &nbsp;
        </label>

    <?php endforeach;?>
        </div>

        <?php if($note) : ?>
        <p class='note message'>
        <?php foreach($note as $v) : ?>
        <span class=""><?php echo $v;?></span>
        <?php endforeach; ?>
        </p>
        <?php endif; ?>

    </dd>

</dl>