<dl class="form">
    <dt>
    <?php if($label) : ?>
        <label for="<?php echo $id;?>"><?php echo $label;?></label>
    <?php endif;?>
    </dt>
    <dd>
        <select name="<?php echo $name;?>" id="<?php echo $id;?>"  class="form-control">
    <?php foreach($options as $key => $option) : ?>
            <option value="<?php echo $option;?>"<?php if($value == $option) : ?> selected<?php endif;?>><?php echo $key;?></option>
    <?php endforeach;?>
        </select>

        <?php if($note) : ?>
        <p class='note message'>
        <?php foreach($note as $v) : ?>
        <span class=""><?php echo $v;?></span>
        <?php endforeach; ?>
        </p>
        <?php endif; ?>

    </dd>
</dl>